// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Prog2_Act03.Models;

public partial class Articulo
{
    public int IdArticulo { get; set; }

    public string? Nombre { get; set; }

    public decimal PrecioUnitario { get; set; }

    public virtual ICollection<DetalleFactura> DetalleFacturas { get; set; } = new List<DetalleFactura>();
}